#!/usr/bin/env python3
"""Import CAD vector metadata to OceanBase/MySQL database

This script imports metadata from JSON files generated by the indexing process
into an OceanBase or MySQL database for advanced querying and filtering.

Usage:
    python scripts/import_metadata_to_oceanbase.py --metadata data/indices/metadata.json
    python scripts/import_metadata_to_oceanbase.py --metadata data/indices/metadata.json --drop-table
    python scripts/import_metadata_to_oceanbase.py --help
"""
import argparse
import json
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from cad_vectordb.database.metadata import MetadataDB
from config import DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME


def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(
        description='Import CAD vector metadata to OceanBase/MySQL',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Import metadata from test index
  python scripts/import_metadata_to_oceanbase.py --metadata data/indices/metadata.json
  
  # Drop existing table and reimport
  python scripts/import_metadata_to_oceanbase.py --metadata data/indices/metadata.json --drop-table
  
  # Custom database connection
  python scripts/import_metadata_to_oceanbase.py \\
    --metadata data/indices/metadata.json \\
    --host 127.0.0.1 \\
    --port 2881 \\
    --user root@test \\
    --password mypass \\
    --database cad_db
  
  # Adjust batch size for large datasets
  python scripts/import_metadata_to_oceanbase.py \\
    --metadata data/indices/metadata.json \\
    --batch-size 5000

For more information, see docs/OCEANBASE_GUIDE.md
        """
    )
    
    # Required arguments
    parser.add_argument(
        '--metadata', '-m',
        type=str,
        required=True,
        help='Path to metadata JSON file (e.g., data/indices/metadata.json)'
    )
    
    # Database connection
    parser.add_argument('--host', type=str, default=DB_HOST, help=f'Database host (default: {DB_HOST})')
    parser.add_argument('--port', type=int, default=DB_PORT, help=f'Database port (default: {DB_PORT})')
    parser.add_argument('--user', type=str, default=DB_USER, help=f'Database user (default: {DB_USER})')
    parser.add_argument('--password', type=str, default=DB_PASSWORD, help='Database password')
    parser.add_argument('--database', '-d', type=str, default=DB_NAME, help=f'Database name (default: {DB_NAME})')
    
    # Import options
    parser.add_argument('--batch-size', type=int, default=1000, help='Batch size for insertion (default: 1000)')
    parser.add_argument('--drop-table', action='store_true', help='Drop existing table before import')
    
    return parser.parse_args()


def main():
    """Main import process"""
    args = parse_args()
    
    print("=" * 60)
    print("CAD Vector Metadata Import to OceanBase/MySQL")
    print("=" * 60)
    print()
    
    # Step 1: Validate metadata file
    print("STEP 1: Validate Metadata File")
    print("-" * 60)
    
    metadata_path = Path(args.metadata)
    if not metadata_path.exists():
        print(f"❌ Metadata file not found: {args.metadata}")
        print(f"\nPlease run the indexing process first:")
        print(f"  python -m cad_vectordb.cli build --data_dir data/vec --output_dir data/indices")
        sys.exit(1)
    
    print(f"✅ Found metadata file: {args.metadata}")
    
    # Load metadata
    try:
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
        print(f"✅ Loaded {len(metadata)} records")
    except Exception as e:
        print(f"❌ Failed to load metadata: {e}")
        sys.exit(1)
    
    print()
    
    # Step 2: Connect to database
    print("STEP 2: Connect to Database")
    print("-" * 60)
    
    db_config = {
        'host': args.host,
        'port': args.port,
        'user': args.user,
        'password': args.password,
        'database': args.database
    }
    
    try:
        db = MetadataDB(**db_config)
        db.connect(create_db=True)
        print(f"✅ Connected to {args.host}:{args.port}/{args.database}")
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        print(f"\nTroubleshooting:")
        print(f"1. Is OceanBase/MySQL running?")
        print(f"   docker ps | grep oceanbase")
        print(f"2. Check connection parameters in config.py")
        print(f"3. For OceanBase, use user format: root@test")
        sys.exit(1)
    
    print()
    
    # Step 3: Create/drop table
    print("STEP 3: Prepare Table")
    print("-" * 60)
    
    try:
        if args.drop_table:
            print("Dropping existing table...")
            with db.conn.cursor() as cur:
                cur.execute("DROP TABLE IF EXISTS `cad_vectors`")
                db.conn.commit()
            print("✅ Table dropped")
        
        db.create_table()
        print("✅ Table `cad_vectors` ready")
    except Exception as e:
        print(f"❌ Table preparation failed: {e}")
        db.close()
        sys.exit(1)
    
    print()
    
    # Step 4: Import metadata
    print("STEP 4: Import Metadata")
    print("-" * 60)
    print(f"Importing {len(metadata)} records (batch_size={args.batch_size})...")
    print()
    
    try:
        stats = db.import_metadata(metadata, batch_size=args.batch_size)
        print()
        print("✅ Import completed successfully!")
        print(f"   Total records: {stats['total']}")
        print(f"   Inserted/Updated: {stats['inserted']}")
    except Exception as e:
        print(f"❌ Import failed: {e}")
        db.close()
        sys.exit(1)
    
    print()
    
    # Step 5: Verify import
    print("STEP 5: Verify Import")
    print("-" * 60)
    
    try:
        db_stats = db.get_stats()
        print(f"✅ Database statistics:")
        print(f"   Total vectors: {db_stats['total_vectors']}")
        print(f"   Unique subsets: {db_stats['unique_subsets']}")
        print(f"   Sequence length: {db_stats['min_seq_len']} - {db_stats['max_seq_len']} (avg: {db_stats['avg_seq_len']:.1f})")
    except Exception as e:
        print(f"⚠️  Verification warning: {e}")
    
    db.close()
    
    print()
    print("=" * 60)
    print("✅ IMPORT COMPLETED SUCCESSFULLY")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Query metadata:")
    print(f"   python scripts/query_metadata_db.py stats")
    print(f"   python scripts/query_metadata_db.py subset 0000")
    print()
    print("2. Use in Python:")
    print("   from cad_vectordb.database.metadata import MetadataDB")
    print(f"   db = MetadataDB('{args.host}', {args.port}, '{args.user}', '***', '{args.database}')")
    print("   db.connect()")
    print("   records = db.query(subset='0000', limit=10)")
    print()


if __name__ == '__main__':
    main()
